[tool.black]
line-length = 79
target-version = ["py310"]

[tool.ruff]
line-length = 79
target-version = "py310"
preview = true
exclude = [
    ".git",
    ".venv",
    "build",
    "dist",
    "node_modules",
    "__pycache__",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "D",
    "UP",
]
ignore = ["E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["app"]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
disallow_untyped_defs = true
exclude = '''
(?x)(
  ^\.git/
  | ^\.venv/
  | ^build/
  | ^dist/
  | ^node_modules/
  | ^__pycache__/
)
'''
